---
test_name: request sessions

# https://tavern.readthedocs.io/en/latest/examples.html
stages:
  - name: 1st Access
    # 
    request:
      url: "http://0.0.0.0:5000/sample/login"
      method: GET

    # ...and the expected response code and body
    response:
      cookies:
        - JSESSIONID
  
  - name: Authenticating
    # 
    request:
      url: "http://0.0.0.0:5000/sample/login"
      method: POST
      cookies:
        - JSESSIONID
      data:
        username: user
        password: password

    # ...and the expected response code and body
    response:
      cookies:
        - JSESSIONID
      status_code: 302
  