---
test_name: request sessions

# https://tavern.readthedocs.io/en/latest/examples.html
stages:
  - name: 1st Access
    # 
    request:
      url: "http://0.0.0.0:5000/sample/login"
      method: GET

    # ...and the expected response code and body
    response:
      cookies:
        - JSESSIONID
      verify_response_with:
        function: tavern.testutils.helpers:validate_regex
        extra_kwargs:
          expression: '<input name=\"_csrf\" type=\"hidden\" value=\".*\" />'
  
  - name: Authenticating
    # 
    request:
      url: "http://0.0.0.0:5000/sample/login"
      method: POST
      cookies:
        - JSESSIONID
      data:
        username: user
        password: password
        #_csrf: "{spring_security:s}"

    # ...and the expected response code and body
    response:
      cookies:
        - JSESSIONID
      status_code: 302
  