version: '3'
services:
  web:
    build: .
    depends_on: 
      - redis

  redis:
    image: "redis:alpine"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
     - "5000:5000"
