version: '3'
services:
  web:
    build:
      .

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
     - "5000:5000"
